dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: "RCUw8bfxfB3FcGkRwlz/fdn3tY6sbsKgojXDbQ9/jwD6yzoXIDCQs/a1s46cN+mlpI81R9ZYU0Xn6AtyCuTP2r9jXSiiaj+l+6DBtysoFnnUvkIz/IwiYJHjVtYiaKwOE7HYpqTcomn6+piRPMaYV9SRsG5pZJDW9wcbVIcaP/xZXgoCwZ/H/gJ67HhnIpij7TVMfkBM1uEfk3i+xMldfs3qgP6onWUeZJ6GKtmVE37JqV6RIX+8VeWDMOfeyS07G8lWszZP39UHhKGGElUuxA1gB/kqQ/j5d1yRkK9PUhRne7f3ZFgWckTqCVosyqW9NMQFWNl7kPaVp6I0zONkpW0q9XjOJtBP530MrPVd2pf0cFPkbFiQ1flJnF3O6jfg1pA8PRqM60K6izRS7YJAqYgtlq6fAqMFhOLXmWBWITRtCWam42FL30km0KLPyTsSi64fxwLMju6k5a6W/G2r8OO5mhkQ9iFq82o6rDNeznr2wQPD0JPnZlzRCcCyEKNwx4AEGttr+2rUMTtuWXfUbh0YTKxFvKqnzMywAQQx+Vif0PvG4CwftW9Srr3yzmZb4N6tZ/aF18aefeLFfLGIhCbYP1WJwPq59WKQPItwiIu124g/bDmGPEP9CukPjq7m7TRvM+gPs6DbFWZadSaG6sO5psmG69/8sKMJD0E/uzE="
  app: $APP
