dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: "KIRz3Pd5mtr8obLl0TBnoHQI83rlN4WTGGbfeRHuVJBJMsThptXeAD2UapP7mid8n6VL0Yo0irT3xM24dns/mF6RCffCNzYeo/GYTU1KjzDbecgeaNCei3u7MyfF1xBrs88F5AP51d6aA5MMGjqvwToQO2moTxqAVXzv4UrVAzpvP9H5lN5pHGK4ZYgHZzgObgNy8JqzR4NgeyN56eQ4EJF0hfvMqtuIZUaD1luR6bur/YpxBrpkJKqyGFru42c/CXbl0vbPz6kin+Q7vZbeCPEV3wPuakA9oibMmfkK6sClQXoOLiBnX1fwH5a03U+KBITFM6xjsFkXK5In03qO6tVYMF1BvECRHP82lmajTEcIrs/UNmXZ+0uGjq2z/PasLztyWV9v4L4gXdTZYoYIPZK/AB8ERu3bqxOy9wBdc688O9HNzNqZD9YntIarfAbI4fWM+xknJy5lgMUYP0PNTqFef54usMz6Q0p1eiauQakfely1lcbq1YHpZQxj4XaOmPD/0TIf+GogGlYunbhUVjG7t3YQVhqZzG4zhyPMUimXm+b/7yuTuDrHt4hd8aW0sMVIE5jNWNEyO2+3I+GusPfnKMjxdCUhmpaQcFFIjy/ixIBvW3q8HI1HHqmLeqDFZ/nuuLQNo/7sbG/G8Fj2Q/CdPnMBFOabhxXpxV0jMC0="
  app: $APP
